builder:
  track: stable

labels:
  app-group: estafette-ci
  type: library
  team: estafette-team
  language: golang

version:
  semver:
    major: 0
    minor: 0
    releaseBranch: main

stages:
  build:
    image: golang:1.15.1-alpine3.12
    env:
      CGO_ENABLED: 0
      GOOS: linux
    commands:
    - go test ./...

  tag-revision:
    image: golang:1.15.1-alpine3.12
    commands:
    - apk add git
    - git tag v${ESTAFETTE_BUILD_VERSION}
    - git push origin v${ESTAFETTE_BUILD_VERSION}

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'succeeded' ||
      status == 'failed'